kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment: 
      token:
        from_secret: token
    commands:
      - dotnet sonarscanner begin 
          /k:"easv-devops_MichaelPayUp_AY3q6z5_EVvRW2O60EQy" 
          /d:sonar.host.url="http://sonar.setgo.dk:9000" 
          /d:sonar.token="$token" 
      - dotnet sonarscanner end /d:sonar.token="$token"