kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands:
      - dotnet sonarscanner begin /k:"easv-devops_MichaelPayUp_AY3q6z5_EVvRW2O60EQy" /d:sonar.host.url="http://sonar.setgo.dk:9000"  /d:sonar.token="sqp_408363c934d9f61dd59445a90268332efcd7a277"
      - cd backend && dotnet build
      - dotnet sonarscanner end /d:sonar.token="sqp_408363c934d9f61dd59445a90268332efcd7a277"